### ISSUE TITLE
Régi > új

### ISSUE THREAD

**Issue by Kafafafi** [gaborauth/calc#1]
Ez van

![fogyi](https://user-images.githubusercontent.com/77679911/180238748-cef1cee5-c98c-441f-bb5e-f666fae7eca0.PNG)

**Comment by gaborauth** [comment]
Valóban, ha a B-tarifa túllépte a 2523 kWh mennyiséget, akkor rosszul számolta a maradék A1-tarifát, javítottam, köszi!
